package constants

const (
	DEVICE_SECRET_KEY = "DEVICE_SECRET_KEY"
	URL_API_SERVICE   = "URL_API_SERVICE"
	SERVICE_SECRET    = "SERVICE_SECRET"

	JWT_ACCESS_SECRET  = "JWT_ACCESS_SECRET"
	JWT_REFRESH_SECRET = "JWT_REFRESH_SECRET"
)
